// Generated by https://quicktype.io

// export interface JSONData {
//     technologies: Technology[];
// }

export interface mainPageProps{
    navNumber:        Function;
}

export interface contactPageProps{
    setLoading:        Function;
}

export interface progressBarProps {
    bgColor: string;
    enable: boolean;
    completed: number;
}