// Generated by https://quicktype.io

// export interface JSONData {
//     technologies: Technology[];
// }

// export interface Technology {
//     name:        string;
//     description: string;
//     difficulty:  number;
//     courses:     Course[];
// }


// Generated by https://quicktype.io

export interface JSONData {
    technologies: Technology[];
    courses:      Course[];
}

export interface Course {
    _id:  string;
    code: string;
    name: string;
}

export interface Technology {
    _id:         string;
    name:        string;
    description: string;
    difficulty:  number;
    courses:     TechnologyCourse[];
}

export interface TechnologyCourse {
    code: string;
    name: string;
}

export interface ComponentProps {
    technologies:Technology[];
    courses:Course[];
}

export interface TechProps {
    technologies:Technology[];
    courses:Course[];
    setLoading:Function;
    setRefreshData:Function;
}

export interface DeleteTechProps {
    technologies:Technology[];
    setLoading:Function;
    setRefreshData:Function;
}

export interface CourseProps {
    courses:Course[];
    setLoading:Function;
    setRefreshData:Function;
}

// export interface CourseCode {
//     code: string;
// }